name: wav_io
description: RIFF-WAV audio file format handling in pure dart.
version: 2.0.1
repository: https://github.com/gnudles/wav_io

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:

#   path: ^1.8.0

dev_dependencies:
  args: ^2.4.0
  test: ^1.16.0
  lints: ^1.0.0
  
