name: wav_io
description: RIFF-WAV audio file format handling and manipulation written in pure dart.
version: 2.0.2
repository: https://github.com/gnudles/wav_io

environment:
  sdk: '>=2.18.0 <4.0.0'


dependencies:

#   path: ^1.8.0

dev_dependencies:
  args: ^2.4.0
  test: ^1.16.0
  lints: ^2.1.1
  
