name: wav_io
description: Wave audio files IO for dart
version: 1.0.0
repository: https://github.com/gnudles/wav_io

environment:
  sdk: '>=2.14.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
