name: wav_io
description: Wave audio files IO for dart
version: 2.0.0
repository: https://github.com/gnudles/wav_io

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:

#   path: ^1.8.0

dev_dependencies:
  args: ^2.4.0
#  lints: ^1.0.0
#  test: ^1.16.0
